# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Trivy Vulnerability Scan

on:
  push:
    branches: ['main']
  pull_request:
    # The branches below must be a subset of the branches above
    branches: ['main']
  schedule:
    - cron: '0 5 * * *'

env:
  IMAGE_NAME: 'aessing/chronyd'

permissions:
  contents: read

jobs:
  build:
    name: Vulnerability scan
    permissions:
      contents: read # for actions/checkout to fetch code
      security-events: write # for github/codeql-action/upload-sarif to upload SARIF results
      actions: read # only required for a private repository by github/codeql-action/upload-sarif to get the Action run status
    runs-on: 'ubuntu-latest'
    steps:
      - name: Checkout code
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Build an image from Dockerfile
        run: |
          docker build -t docker.io/${{ env.IMAGE_NAME }}:trivy-${{ github.sha }} .

      - name: Run Trivy vulnerability scanner (image)
        uses: aquasecurity/trivy-action@b6643a29fecd7f34b3597bc6acb0a98b03d33ff8
        with:
          image-ref: 'docker.io/${{ env.IMAGE_NAME }}:trivy-${{ github.sha }}'
          format: 'sarif'
          output: 'trivy-image-results.sarif'
          severity: 'CRITICAL,HIGH'
          exit-code: '0'

      - name: Run Trivy vulnerability scanner (requirements.txt)
        uses: aquasecurity/trivy-action@b6643a29fecd7f34b3597bc6acb0a98b03d33ff8
        with:
          scan-type: 'fs'
          scan-ref: '.'
          format: 'sarif'
          output: 'trivy-py-results.sarif'
          severity: 'CRITICAL,HIGH'
          exit-code: '0'

      - name: Upload Trivy image scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@cdefb33c0f6224e58673d9004f47f7cb3e328b89
        with:
          sarif_file: 'trivy-image-results.sarif'
          category: 'trivy-image'

      - name: Upload Trivy Python scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@cdefb33c0f6224e58673d9004f47f7cb3e328b89
        with:
          sarif_file: 'trivy-py-results.sarif'
          category: 'trivy-python'

      - name: Docker cleanup
        run: |
          docker rmi docker.io/${{ env.IMAGE_NAME }}:trivy-${{ github.sha }} || true
